name: GH- example

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script 
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    steps: 
      - name: Directory powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: log node version
        run: node -v 
